package br.com.zup.Projeto.TiposDeDonativos;

public enum OsTiposDeDonativos
{
    ALIMENTOS,
    HIGIENEPESSOAL,
    MEDICAMENTOS,
    VESTIMENTAS,
    MIDIA,
    MIDIAEDUCATIVA,
    BENSDECONSUMO,
    BENSDECONSUMODURAVEIS,
    MATERIAPRIMA,
    MATERIALRECICLADO
}
